### Base Image
FROM ubuntu:latest

### Update OS
RUN apt update && \
	apt install software-properties-common -y && \
	add-apt-repository ppa:deadsnakes/ppa -y
	
### Install Python
RUN apt install python3.8 -y && \
	apt install python3-pip -y

COPY . .

RUN pip3 install -r requirements.txt

CMD ["python3", "main.py"]